services:
  client:
    build:
      context: ./client
    container_name: fca-client
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      BACKEND_HOST: ${BACKEND_HOST}
      BACKEND_PORT: "7777"
